### ISSUE TITLE
Can't paste code

### ISSUE THREAD

**Issue by davidleiti** [raycoarana/material-code-input#17]
Hi, I've been trying to use the library for a verification flow where the user can enter a 6 digit code received in an SMS message, but as far as I could see the library doesn't allow/support pasting the received code, neither with a long click or directly from the keyboard (in this case the action just seems lost) and it has to be typed in manually. 

Is this something that there will be future support for, or is it already and am I missing something?

Thanks a lot, 
David

**Comment by raycoarana** [comment]
Hi, by pasting you mean tap/long tap and select Paste from the pop menu? I don't think that is supported actually, but I think it should work with the autocomplete feature of Android when SMS with a code is received.

**Comment by davidleiti** [comment]
Yes, I meant either the long tap and Paste from the pop menu (which I understand that it's not supported), or pasting directly from the keyboard suggestion when a code is copied from somewhere, which doesn't seem to work with the CodeInputView.

I will look into the autocomplete approach and let you know if it works out, thanks!

**Comment by raycoarana** [comment]
Check this doc: https://developers.google.com/identity/sms-retriever, it describes how to adapt your SMS flow so that the OS offers the autocomplete.

**Comment by davidleiti** [comment]
Yeah, I've managed to implement it just now, works great with the CodeInputView.

Thanks for the suggestion, and great job on the library!
