### ISSUE TITLE
CodeInputView not shown after completing the code

### ISSUE THREAD

**Issue by xtianpu** [raycoarana/material-code-input#2]
But when I press delete on softkeyboard the CodeInputView show up.

**Comment by raycoarana** [comment]
Hi, could you please elaborate more your problem? By default in the animated mode, the CodeInputView hides the code with an animation or just hide it completely after completing the code. This way, the programer could show a ProgressBar while the code is confirmed.

**Comment by xtianpu** [comment]
It hide completely and I dont see any method to show the view again. I want exactly like the GIF at readme.md which showing up after oncompletion of the code. Thank you.

**Comment by raycoarana** [comment]
That is done after showing an error, call the method `setError` to reshow the code with the error in that case.

**Comment by xtianpu** [comment]
I've tried setError it only show a red text but codeinputview not showing anymore, kindly check it out.

**Comment by raycoarana** [comment]
I would need more information, actually in the sample project is working, you have to call setError to reset the view and display the error to the user, the code input is shown again in that case.

**Comment by CallumCoombes** [comment]
I think I have encountered the same issue. Upon completion of a correct code, the code-input-view hides. There doesn't seem to be a method to reset the code-input-view to a non-error state, it just remains hidden. It would be good to have a reset method that clears everything and shows the code-input-view in the starting state.

**Comment by CallumCoombes** [comment]
However a current workaround is just to call:
```
codeInputView.setError("");
codeInputView.clearError();
codeInputView.setCode("");
codeInputView.setEditable(true);
```
This will reset it to an empty and editable state.

**Comment by Subarata-Talukder** [comment]
I used this code in my root linear layout but CodeInputView not shown in my real device after build the project.

<com.raycoarana.codeinputview.CodeInputView
    android:layout_marginTop="20dp"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:underline_color="#457ad1"
    app:underline_selected_color="#9e1ace"
    app:code_text_color="#b12eff"
    app:error_color="#77ce9d"
    app:input_type="numeric"
    app:length_of_code="4" />
