### ISSUE TITLE
Keyboard doesn't appear

### ISSUE THREAD

**Issue by sharon-makaron** [raycoarana/material-code-input#5]
Hello, when I open dialog with InputView, keyboard doesn't appear. I mean other don't see any problems with this...

**Comment by sharon-makaron** [comment]
Workaround: I created an invisible edittext that requested focus and soft keyboard appeared.

**Comment by raycoarana** [comment]
In the current version, just providing focus to the input should show the keyboard.

I'm closing this, in case it is still not working for you, let me know.
